version: '3'
services:
  db:
    container_name: raf_db
    image: postgres:10.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: raf
      POSTGRES_USER: raf
      POSTGRES_PASSWORD: password
  db-admin:
    container_name: raf_dbadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "6432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raf@raf.com
      PGADMIN_DEFAULT_PASSWORD: password